### ISSUE TITLE
Calling R from Rust on Windows 32bit is broken

### ISSUE THREAD

**Issue by clauswilke** [extendr/libR-sys#29] opened 2020-12-16 06:32 UTC
The latest version of the libR-sys precompiled bindings for Windows compile on 32 bit (https://github.com/extendr/helloextendr/runs/1561836399?check_suite_focus=true#step:11:174), but `cargo test` still fails for libR-sys (https://github.com/extendr/libR-sys/runs/1561658815#step:7:218), with an error that suggests a linking problem. I'm starting to think that this is because the code we use to call R from Rust is a bit naive, and basically assumes a unix-like system:
https://github.com/extendr/libR-sys/blob/73e57498c238615072f0742347599517a29726d7/src/lib.rs#L74-L86
(I'm linking here to code where I've tried to fix this up a bit, but still there may be a fundamental problem with this approach on Windows, in particular on 32 bit.)

The R documentation describes two entirely different approaches to embedding R from external code, one for Unix and one for Windows:
https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Linking-GUIs-and-other-front_002dends-to-R
 
Also, on systems with multiple architectures (such as Windows) we should not assume that the call to `Rf_initialize_R()` can automatically find the correct runtime to start:
https://cran.r-project.org/doc/manuals/R-admin.html#Sub_002darchitectures
Setting the `--arch` flag may help (but didn't fix the issues here).

**Comment by clauswilke** [comment] 2020-12-16 06:39
@Ilia-Kosenkov Would you mind reproducing this workflow:
https://github.com/clauswilke/libR-sys/blob/73e57498c238615072f0742347599517a29726d7/.github/workflows/test.yml#L139
using this branch:
https://github.com/clauswilke/libR-sys/tree/precomputed_bindings
and testing what happens that causes this crash:
https://github.com/extendr/libR-sys/pull/27/checks?check_run_id=1561658815#step:7:218

It looks like a library mismatch or missing symbol in one of the libraries, so stepping through the loading process like you did the other day should uncover what the problem is. I suspect that either the 32-bit Rust binary is trying to link to the 64-bit R runtime or that it is trying to call a function that simply doesn't exist in 32-bit R.

**Comment by clauswilke** [comment] 2020-12-17 15:33
The branch I linked to in the previous comment doesn't exist anymore. It's been merged into https://github.com/extendr/libR-sys/.

**Comment by Ilia-Kosenkov** [comment] 2020-12-17 15:37
@clauswilke,
I somehow missed this issue, I will try reproducing if it still makes sense.

**Comment by clauswilke** [comment] 2020-12-17 15:40
Yes, please do, I'd like to know why the tests crash. Curiously they crash even if I comment out any calls to libR-sys, so it may be a similar problem to the libclang problem you found.

**Comment by Ilia-Kosenkov** [comment] 2020-12-17 17:38
@clauswilke,
Got the same error as your GHA.
From `WinDbgX` here is what (I guess) is wrong:

<details>

```
ModLoad: 00000000`774b0000 00000000`774b9000   C:\Windows\System32\wow64cpu.dll
ModLoad: 00000000`76f70000 00000000`77050000   C:\Windows\SysWOW64\KERNEL32.DLL
ModLoad: 00000000`76b80000 00000000`76d7f000   C:\Windows\SysWOW64\KERNELBASE.dll
ModLoad: 00000000`76680000 00000000`766f9000   C:\Windows\SysWOW64\ADVAPI32.dll
ModLoad: 00000000`75680000 00000000`7573f000   C:\Windows\SysWOW64\msvcrt.dll
ModLoad: 00000000`76130000 00000000`761a6000   C:\Windows\SysWOW64\sechost.dll
ModLoad: 00000000`76870000 00000000`7692b000   C:\Windows\SysWOW64\RPCRT4.dll
ModLoad: 00000000`74c80000 00000000`74ca5000   C:\Windows\SysWOW64\SspiCli.dll
ModLoad: 00000000`74c70000 00000000`74c7a000   C:\Windows\SysWOW64\CRYPTBASE.dll
ModLoad: 00000000`76e70000 00000000`76ecf000   C:\Windows\SysWOW64\bcryptPrimitives.dll
ModLoad: 00000000`76e10000 00000000`76e6e000   C:\Windows\SysWOW64\WS2_32.dll
ModLoad: 00000000`72cd0000 00000000`72cee000   C:\Windows\SysWOW64\USERENV.dll
ModLoad: 00000000`76930000 00000000`76a50000   C:\Windows\SysWOW64\ucrtbase.dll
ModLoad: 00000000`76a60000 00000000`76a7b000   C:\Windows\SysWOW64\profapi.dll
ModLoad: 00000000`6c700000 00000000`6f8a7000   C:\Program Files\R\R-4.0.3\bin\x64\R.dll
ntdll!NtWaitForWorkViaWorkerFactory+0x14:
00007ff9`5ab60084 c3              ret
```

</details>

Last pulled `.dll` is from `x64` folder.
Take a look [here](https://docs.microsoft.com/en-us/windows-hardware/drivers/bringup/authoring-an-update-driver-package), there is one entry in the table at the bottom that mentions the error code you get

`Error: Invalid Image Format | 4 | STATUS_INVALID_IMAGE_FORMAT | 0xC000007B`

This error is typical if you mix `32` and `64` bit libs.

**Comment by clauswilke** [comment] 2020-12-17 17:44
Thanks, this is exactly what I thought the error was. Not sure why this happens, though, since we're setting the correct link path (`cargo:rustc-link-search`, see here: https://github.com/extendr/libR-sys/pull/27/checks?check_run_id=1561658815#step:6:240). Maybe it's also related to the `cargo run` problem we've discovered.

**Comment by Ilia-Kosenkov** [comment] 2020-12-17 17:49
I will try looking into this -- maybe I can find something, but no promises.

**Comment by Ilia-Kosenkov** [comment] 2020-12-17 18:08
@clauswilke,
Found the problem, at least on my machine.
I have `R\x64\bin` added to my PATH so I can invoke `R.exe` from anywhere. 
This gets included as `PATH` variable and probably spoils the linkage, as the same folder contains `R.dll`.

If I remove this from my `PATH`, I now get `DLL_NOT_FOUND`, so `cargo` does not respect whatever include path you provide.

```Caused by:
  process didn't exit successfully: `C:\Users\[redacted]\source\repos\libR-sys\target\i686-pc-windows-gnu\release\deps\libR_sys-26b9d7f725f7b0b7.exe --nocapture --test-threads=1` (exit code: 0xc0000135, STATUS_DLL_NOT_FOUND)```

**Comment by Ilia-Kosenkov** [comment] 2020-12-17 18:33
I completely forgot that I can simply add `bin\i386` to my path to see if tests succeed.
Well, they do, I guess, hooray to that.

<details>

```
    Finished test [unoptimized + debuginfo] target(s) in 0.05s
     Running target\i686-pc-windows-gnu\debug\deps\libR_sys-661db4faad5bd979.exe
   Doc-tests libR-sys

running 1 test
test tests::test_eval ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.15s

[1] 1

running 1 test
test src\lib.rs - (line 18) ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.06s
```

</details>

**Comment by Ilia-Kosenkov** [comment] 2020-12-18 20:26
Other projects are facing similar issues, see e.g. [this discussion](https://github.com/rust-lang/cargo/issues/4895).

**Comment by Ilia-Kosenkov** [comment] 2020-12-29 20:21
I suggest closing this issue for now because we have builds and tests running correctly for both architectures of Windows,
see e.g.
https://github.com/extendr/libR-sys/actions/runs/451396530

**Closed by Ilia-Kosenkov** 2020-12-29 20:21 UTC
