### ISSUE TITLE
CI failure

### ISSUE THREAD

**Issue by yutannihilation** [extendr/libR-sys#151] opened 2023-04-08 13:58 UTC
https://github.com/extendr/libR-sys/actions/runs/4640105301 
```
  error[E0425]: cannot find value `R_CStackLimit` in this scope
     --> src\lib.rs:128:17
      |
  128 |                 R_CStackLimit = usize::max_value();
      |                 ^^^^^^^^^^^^^
      |
  help: you might have meant to introduce a new binding
      |
  128 |                 let R_CStackLimit = usize::max_value();
      |                 +++
  
  error[E0412]: cannot find type `ParseStatus` in this scope
     --> src\lib.rs:145:29
      |
  145 |             let mut status: ParseStatus = 0;
      |                             ^^^^^^^^^^^ not found in this scope
  
  error[E0412]: cannot find type `ParseStatus` in this scope
     --> src\lib.rs:146:50
      |
  146 |             let status_ptr = &mut status as *mut ParseStatus;
      |                                                  ^^^^^^^^^^^ not found in this scope
```

My guess is that this is the core is the problem. Maybe the underlying clang changed the options?

```
  [libR-sys 0.4.0] cargo:warning=unused option: --allowlist-var 
```

**Comment by Ilia-Kosenkov** [comment] 2023-04-08 14:08
I suspect also this: it does not recognize `--allowlist-function`

 https://github.com/extendr/libR-sys/actions/runs/4640105301/jobs/8218573032#step:14:98

**Comment by yutannihilation** [comment] 2023-04-08 14:11
Yeah, I meant these `--allowlist-*` options.

**Comment by Ilia-Kosenkov** [comment] 2023-04-08 14:21
I am gonna update my local setup (including MSYS) to check if I can reproduce this. Searching relevant repos gave me nothing, and the fact it fails strictly on Windows suggests it is something MSYS-related

**Comment by Ilia-Kosenkov** [comment] 2023-04-09 09:26
Confirmed locally. I'll look into this & if it can be patched temporarily

**Comment by Ilia-Kosenkov** [comment] 2023-04-09 11:02
Since MSYS seems to provide only the latest version of any package, I had to resort to compiling bindings using native installation of `llvm`. Using chocolatey versioning, I can reliably reproduce that on `llvm 15.0.7` (latest `15.x.x` version), things work as before, but on `llvm 16.0.0` it breaks. So two takeaway messages:
1) We can compile bindings on Windows using native llvm and Rtools, no need for MSYS
2) Something has changed between `15.0.7` and `16.0.0` that affects bindgen (or maybe clang) rust crates

**Comment by Ilia-Kosenkov** [comment] 2023-04-09 11:26
Filed an issue at bindgen https://github.com/rust-lang/rust-bindgen/issues/2488 . Let's see if they can point us in the right direction.

**Comment by yutannihilation** [comment] 2023-04-12 02:27
(Note to self) This is the anonymous enum in question.

https://github.com/r-devel/r-svn/blob/9d9ba44635ff918ce2e1254a0c820d55cfed050b/src/include/Rinternals.h#L1144-L1150

**Comment by CGMossa** [comment] 2023-04-12 11:56
Closing this since #154 fixes this.
Now on to the `Rcomplex` mess.

**Closed** 2023-04-12 11:56 UTC
Labels: bug, os-Windows
